name: print 'hello world'

on:
  schedule:
    - cron: '10 14 * * *'    # 8am local, 2pm UTC
    - cron: '10 17 * * *'    # noon local, 6pm UTC
    - cron: '10 21 * * *'    # 4pm local, 10pm UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: /actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script    # run main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python main_run_1.py
