name: run test_automate.py

on:
  schedule:
   - cron: '*/5 * * * *'  # every 5 minutes, keeping it fast enough to see

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: execute py script
        env:
          API_KEY: ${{  secrets.API_KEY }}
        run: python test_automate.py
